### ISSUE TITLE
Would this work for ubuntu on odroid-c2?

### ISSUE THREAD

**Issue by TrevorScheitrum** [gustaebel/zfs-aarch64#1]
Hi, i'm trying to get Native ZFS working on an odroid-c2 running ubuntu 16.04 ARM.  If I clone this and build the repo, would this work on ubuntu?  If not any suggestions in what i would need to change to get it to compile and run on ubuntu?

**Comment by gustaebel** [comment]
No, but the Ubuntu wiki claims that there is an official package since 16.04 ([https://wiki.ubuntu.com/Kernel/Reference/ZFS](url)). If that does not work for you, you have to manually build spl and zfs from source (./configure && make && make install), which is pretty straightforward. Take a look at spl/PKGBUILD and zfs/PKGBUILD on how I do it.
